### ISSUE TITLE
Data for Brannin function

### ISSUE THREAD

**Issue by alexandraday-nu** [deephyper/tutorials#8]
Looking for data file referenced in tutorial 6 for the Brannin function.  Seems to be missing from tutorials page.  Also - is tutorial 6 compatible with image input data?

**Comment by Deathn0t** [comment]
Hello,

Could you please share the link of the tutorial your are mentionning?

**Comment by alexandraday-nu** [comment]
https://github.com/deephyper/tutorials/blob/main/tutorials/notebooks/06_NAS_with_Multi_Inputs/tutorial_06.ipynb

"This dataset is provided in the deephyper/tutorials repository."

However, I don't see it under that repo.  Thanks!

**Comment by Romit-Maulik** [comment]
While we look for the specific data set - please look at Figure 4 in the article here:
https://link.springer.com/article/10.1007/s00158-014-1213-9

That will help you generate the same data set

**Comment by Deathn0t** [comment]
Hello @alexandraday-nu , sorry for the delay. We added the missing data 
https://github.com/deephyper/tutorials/blob/main/tutorials/notebooks/06_NAS_with_Multi_Inputs/data.npz
